version: 2
updates:
  - package-ecosystem: npm
    directory: /
    # Disable updates except for vulnerabilities
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      actions:
        patterns:
          - '@actions/*'
  - package-ecosystem: github-actions
    directory: /
    # Disable updates except for vulnerabilities
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"
      include: "scope"