name: 'Build and Push to Humanitec'
description: 'Builds a container image from a Dockerfile and then pushes it to the Humanitec registry and notifies the platform.'
inputs:
  humanitec-token:
    description: |
      API Token provided when you add your ci pipline in the Humanitec platform.
    required: true
  organization:
    description: 'The name of the organization that the image will be built for.'
    required: true
  image-name:
    description: 'The name you want to refer to the image to in the Humanitec Platform.'
    required: false
    default: ''
  existing-image:
    description: 'Use an existing image instead of building an image. The image name needs to include a tag or digest.'
    required: false
    default: ''
  commit:
    description: 'Use commit when you want to specify non-default commit SHA (GITHUB_SHA).'
    required: false
  tag:
    description: 'Use tag when you want to bring your own tag.'
    required: false
  ref:
    description: 'Use ref when you want to bring your own ref instead of the GitHub action supplied ref.'
    required: false
  auto-tag:
    description: 'Use auto-tag when you want to push tags/release by their git name.'
    required: false
  dockerfile:
    description: 'The same as "context".'
    required: false
    deprecationMessage: 'Use "context" instead.'
  context:
    description: 'Build context path. Defaults to the root of repository.'
    required: false
    default: '.'
  file:
    description: 'Name of the Dockerfile, defaults to `$context/Dockerfile`.'
    required: false
  additional-docker-arguments:
    description: 'Additional arguments for docker (e.g.,build arguments). Defaults to empty.'
    required: false
  humanitec-registry:
    description: 'Allows the default humanitec registry to be overidden for testing.'
    required: false
    default: 'registry.humanitec.io'
  humanitec-api:
    description: 'Allows the default humanitec api to be overidden for testing.'
    required: false
    default: 'api.humanitec.io'
  external-registry-url:
    description: 'Push the image to an external container registry. This registry does not need to be [registered with Humanitec](https://docs.humanitec.com/guides/connect-ci-setup/container-registries) and authentication needs to be done by the explicitly (e.g. using workload identity).'
    required: false
    default: ''
outputs:
  image:
    description: 'The full name of the image that was built and pushed.'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'check-square'
  color: 'blue'
